<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.kie.kogito</groupId>
		<artifactId>kogito-runtimes</artifactId>
		<version>10.1.0</version>
	</parent>

	<groupId>cn.sparrowmini</groupId>
	<artifactId>sparrow-bpm-server-quarkus</artifactId>
<!--	<version>0.0.1</version>-->
	<packaging>jar</packaging>
	<properties>
		<java.version>17</java.version>
		<hibernate.version>6.6.26.Final</hibernate.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<quarkus-plugin.version>3.15.3</quarkus-plugin.version>
		<quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
		<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
		<quarkus.platform.version>3.15.3</quarkus.platform.version>
		<kogito.bom.group-id>org.kie.kogito</kogito.bom.group-id>
		<kogito.bom.artifact-id>kogito-bom</kogito.bom.artifact-id>
		<kogito.bom.version>10.1.0</kogito.bom.version>
		<version.org.kie.kogito>10.1.0</version.org.kie.kogito>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>${quarkus.platform.artifact-id}</artifactId>
				<version>${quarkus.platform.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>${kogito.bom.group-id}</groupId>
				<artifactId>${kogito.bom.artifact-id}</artifactId>
				<version>${kogito.bom.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>jakarta.data</groupId>
			<artifactId>jakarta.data-api</artifactId>
			<version>1.0.0</version>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-orm</artifactId>
		</dependency>
		<dependency>
			<groupId>cn.sparrowmini</groupId>
			<artifactId>sparrow-bpm-api</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-oidc</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-oidc-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.microprofile.rest.client</groupId>
			<artifactId>microprofile-rest-client-api</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jbpm</groupId>
			<artifactId>jbpm-with-drools-quarkus</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-openapi</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-health</artifactId>
		</dependency>

		<dependency>
			<groupId>org.drools</groupId>
			<artifactId>drools-quarkus-rules</artifactId>
		</dependency>

		<dependency>
			<groupId>org.kie.kogito</groupId>
			<artifactId>jbpm-usertask</artifactId>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.kie/kogito-addons-quarkus-data-audit-jpa -->
		<dependency>
			<groupId>org.kie</groupId>
			<artifactId>kogito-addons-quarkus-data-audit-jpa</artifactId>
			<version>${version}</version>
		</dependency>
		<dependency>
			<groupId>org.kie</groupId>
			<artifactId>kogito-addons-quarkus-data-audit</artifactId>
			<version>${version}</version>
		</dependency>
		<dependency>
			<groupId>org.jbpm</groupId>
			<artifactId>jbpm-addons-quarkus-usertask-storage-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jdbc-postgresql</artifactId>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>io.quarkus</groupId>-->
<!--			<artifactId>quarkus-hibernate-orm-panache</artifactId>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.kie</groupId>
			<artifactId>kie-addons-quarkus-persistence-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.kie.kogito</groupId>
			<artifactId>process-workitems</artifactId>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>org.jbpm</groupId>-->
<!--			<artifactId>jbpm-addons-quarkus-task-management</artifactId>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.kie</groupId>
			<artifactId>kie-addons-quarkus-process-management</artifactId>
		</dependency>
		<dependency>
			<groupId>org.kie</groupId>
			<artifactId>kie-addons-quarkus-process-svg</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jbpm</groupId>
			<artifactId>jbpm-addons-quarkus-mail</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jbpm</groupId>
			<artifactId>jbpm-addons-quarkus-task-notification</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-messaging-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.38</version>
			<scope>compile</scope>
		</dependency>
    </dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>quarkus-maven-plugin</artifactId>
				<version>${quarkus-plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>17</source>
					<target>17</target>
					<encoding>UTF-8</encoding>
					<compilerArgs>
						<arg>-parameters</arg>
					</compilerArgs>
                    <generatedSourcesDirectory>target/generated-sources</generatedSourcesDirectory>
					<annotationProcessorPaths>
						<path>
							<groupId>org.hibernate.orm</groupId>
							<artifactId>hibernate-jpamodelgen</artifactId>
							<version>${hibernate.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.30</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>