version: '3.8'

services:
  solr:
    image: solr:10.0
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    # No more -c! Solr 10 defaults to Cloud mode.
    command:
      - solr-foreground
    environment:
      - SOLR_COLLECTION=gettingstarted

volumes:
  data: