pipeline {
    agent { label 'dengbo-fedora' }

    environment {
        IMAGE_NAME = 'sparrow-bpm-server'
        IMAGE_TAG = "${env.GIT_COMMIT.take(7)}"
        JAVA_HOME = '/usr/lib/jvm/java-11-openjdk'
        PATH = "${env.JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Deploy') {
            steps {
                dir('sparrow-bpm-server') {   // 👈 切换到子目录
                    sh 'mvn clean package -DskipTests'
                    sh """
                        docker build -f src/main/docker/Dockerfile -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    """
                    configFileProvider([configFile(fileId: 'dengbo-bpm.yml', targetLocation: 'docker-compose.yml')]) {
                        sh '''
                            docker compose -f docker-compose.yml up -d --remove-orphans
                        '''
                    }
                }
            }
        }
    }

    post {
        failure {
            echo '💥 构建失败，请检查日志'
        }
        success {
            echo '✅ 服务已成功构建并部署'
        }
    }
}
