/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CaseFileDataItem { 
    caseId?: string;
    name?: string;
    value?: string;
    type?: string;
    lastModifiedBy?: string;
    lastModified?: Date;
}
