/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CaseInstanceCustomVars { 
    processInstanceId?: number;
    caseId?: string;
    caseDefinitionId?: string;
    processName?: string;
    processVersion?: string;
    state?: number;
    containerId?: string;
    initiator?: string;
    correlationKey?: string;
    processVariables?: { [key: string]: any; };
    caseVariables?: { [key: string]: any; };
}
