/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Escalation } from './escalation';
import { I18NText } from './i18NText';

export interface Deadline { 
    date?: Date;
    id?: number;
    escalated?: boolean;
    documentation?: Array<I18NText>;
    escalations?: Array<Escalation>;
}