/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrganizationalEntity } from './organizationalEntity';

export interface Delegation { 
    delegates?: Array<OrganizationalEntity>;
    allowed?: Delegation.AllowedEnum;
}
export namespace Delegation {
    export type AllowedEnum = 'Anybody' | 'Nobody' | 'PotentialOwners' | 'Other';
    export const AllowedEnum = {
        Anybody: 'Anybody' as AllowedEnum,
        Nobody: 'Nobody' as AllowedEnum,
        PotentialOwners: 'PotentialOwners' as AllowedEnum,
        Other: 'Other' as AllowedEnum
    };
}