/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ExecutionErrorInstance { 
    errorId?: string;
    type?: string;
    containerId?: string;
    processInstanceId?: number;
    processId?: string;
    activityId?: number;
    activityName?: string;
    jobId?: number;
    errorMessage?: string;
    error?: string;
    acknowledged?: boolean;
    acknowledgedBy?: string;
    acknowledgedAt?: Date;
    errorDate?: Date;
}
