/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FilterTreeBean { 
    type?: FilterTreeBean.TypeEnum;
    name?: string;
    op?: string;
    value?: any;
    not?: boolean;
}
export namespace FilterTreeBean {
    export type TypeEnum = 'AND' | 'OR';
    export const TypeEnum = {
        AND: 'AND' as TypeEnum,
        OR: 'OR' as TypeEnum
    };
}