/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Message { 
    severity?: Message.SeverityEnum;
    timestamp?: Date;
    messages?: Array<string>;
}
export namespace Message {
    export type SeverityEnum = 'INFO' | 'WARN' | 'ERROR';
    export const SeverityEnum = {
        INFO: 'INFO' as SeverityEnum,
        WARN: 'WARN' as SeverityEnum,
        ERROR: 'ERROR' as SeverityEnum
    };
}
