/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MigrationReportInstance { 
    successful?: boolean;
    startDate?: Date;
    endDate?: Date;
    logs?: Array<string>;
    processInstanceId?: number;
}
