/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NodeInstance { 
    id?: number;
    name?: string;
    processInstanceId?: number;
    workItemId?: number;
    containerId?: string;
    date?: Date;
    nodeId?: string;
    nodeType?: string;
    connection?: string;
    completed?: boolean;
    referenceId?: number;
    slaCompliance?: number;
    slaDueDate?: Date;
}
