/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { I18NText } from './i18NText';
import { OrganizationalEntity } from './organizationalEntity';

export interface Notification { 
    names?: Array<I18NText>;
    priority?: number;
    id?: number;
    documentation?: Array<I18NText>;
    notificationType?: Notification.NotificationTypeEnum;
    businessAdministrators?: Array<OrganizationalEntity>;
    subjects?: Array<I18NText>;
    descriptions?: Array<I18NText>;
    recipients?: Array<OrganizationalEntity>;
}
export namespace Notification {
    export type NotificationTypeEnum = 'Default' | 'Email';
    export const NotificationTypeEnum = {
        Default: 'Default' as NotificationTypeEnum,
        Email: 'Email' as NotificationTypeEnum
    };
}