/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskSummaryList } from './taskSummaryList';


export interface ProcessInstanceCustomVars { 
    id?: number;
    processId?: string;
    processName?: string;
    processVersion?: string;
    state?: number;
    containerId?: string;
    initiator?: string;
    date?: Date;
    processInstanceDescription?: string;
    correlationKey?: string;
    parentId?: number;
    lastModificationDate?: Date;
    activeUserTasks?: TaskSummaryList;
    variables?: { [key: string]: any; };
}
