/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ServiceResponseObject { 
    type?: ServiceResponseObject.TypeEnum;
    msg?: string;
    result?: any;
}
export namespace ServiceResponseObject {
    export type TypeEnum = 'SUCCESS' | 'FAILURE' | 'NO_RESPONSE';
    export const TypeEnum = {
        SUCCESS: 'SUCCESS' as TypeEnum,
        FAILURE: 'FAILURE' as TypeEnum,
        NORESPONSE: 'NO_RESPONSE' as TypeEnum
    };
}
