/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TaskEventInstance { 
    id?: number;
    taskId?: number;
    type?: string;
    userId?: string;
    logTime?: Date;
    processInstanceId?: number;
    workItemId?: number;
    message?: string;
    correlationKey?: string;
    processType?: number;
    assignedOwner?: string;
}
