/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Deadlines } from './deadlines';
import { Delegation } from './delegation';
import { I18NText } from './i18NText';
import { PeopleAssignments } from './peopleAssignments';
import { TaskData } from './taskData';

export interface TaskImpl { 
    id?: number;
    version?: number;
    priority?: number;
    name?: string;
    subject?: string;
    description?: string;
    names?: Array<I18NText>;
    subjects?: Array<I18NText>;
    descriptions?: Array<I18NText>;
    peopleAssignments?: PeopleAssignments;
    delegation?: Delegation;
    taskData?: TaskData;
    deadlines?: Deadlines;
    subTaskStrategy?: TaskImpl.SubTaskStrategyEnum;
    taskType?: string;
    formName?: string;
    archived?: boolean;
}
export namespace TaskImpl {
    export type SubTaskStrategyEnum = 'NoAction' | 'EndParentOnAllSubTasksEnd' | 'SkipAllSubTasksOnParentSkip';
    export const SubTaskStrategyEnum = {
        NoAction: 'NoAction' as SubTaskStrategyEnum,
        EndParentOnAllSubTasksEnd: 'EndParentOnAllSubTasksEnd' as SubTaskStrategyEnum,
        SkipAllSubTasksOnParentSkip: 'SkipAllSubTasksOnParentSkip' as SubTaskStrategyEnum
    };
}