/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TaskInstance { 
    id?: number;
    priority?: number;
    name?: string;
    subject?: string;
    description?: string;
    taskType?: string;
    formName?: string;
    status?: string;
    actualOwner?: string;
    createdBy?: string;
    createdOn?: Date;
    activationTime?: Date;
    expirationDate?: Date;
    skipable?: boolean;
    workItemId?: number;
    processInstanceId?: number;
    parentId?: number;
    processId?: string;
    containerId?: string;
    slaCompliance?: number;
    slaDueDate?: Date;
    potentialOwners?: Array<string>;
    excludedOwners?: Array<string>;
    businessAdmins?: Array<string>;
    inputData?: { [key: string]: any; };
    outputData?: { [key: string]: any; };
    correlationKey?: string;
    processType?: number;
}
