/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TaskSummary { 
    id?: number;
    name?: string;
    subject?: string;
    description?: string;
    status?: string;
    priority?: number;
    skipable?: boolean;
    actualOwner?: string;
    createdBy?: string;
    createdOn?: Date;
    activationTime?: Date;
    expirationTime?: Date;
    processInstanceId?: number;
    processId?: string;
    containerId?: string;
    parentId?: number;
    correlationKey?: string;
    processType?: number;
}
