/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskSummary } from './taskSummary';


export interface TaskSummaryList { 
    tasks?: Array<TaskSummary>;
    items?: Array<TaskSummary>;
}
