/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TimerInstance { 
    timerName?: string;
    id?: number;
    timerId?: number;
    activationTime?: Date;
    lastFireTime?: Date;
    nextFireTime?: Date;
    delay?: number;
    period?: number;
    repeatLimit?: number;
    processInstanceId?: number;
    sessionId?: number;
}
