/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserTaskDefinition { 
    id?: string;
    name?: string;
    priority?: number;
    comment?: string;
    createdBy?: string;
    skippable?: boolean;
    formName?: string;
    associatedEntities?: Array<string>;
    taskInputMappings?: { [key: string]: string; };
    taskOutputMappings?: { [key: string]: string; };
}
