server.port=8601

#hibernate configuration
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
#spring.datasource.initialization-mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.org.hibernate.envers.audit_table_prefix=au_
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.jackson.serialization.fail-on-empty-beans=false
# keycloak security setup
#keycloak.public-client=true
keycloak.principal-attribute=preferred_username
#keycloak.bearer-only=true
#need to set true, otherwise it will use realm role default
#keycloak.use-resource-role-mappings=true
#keycloak.enable-basic-auth=true
#keycloak oauth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
spring.main.allow-circular-references=true
server.servlet.context-path=/chnplc-service

application.name=@project.artifactId@
application.description=
build.version=@project.version@
build.timestamp=@timestamp@

springdoc.swagger-ui.operationsSorter=alpha
#For sorting tags alphabetically
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-operation-id=true
#springdoc.api-docs.groups.enabled=true
#springdoc.group-configs[0].group=Purchase
#springdoc.group-configs[0].packages-to-scan=cn.liyun
#
#springdoc.group-configs[1].group=Sparrow
#springdoc.group-configs[1].packages-to-scan=cn.sparrowmini

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.cn.sparrowmini=DEBUG
logging.level.cn.liyuan=DEBUG


zk.homepage=index
zk.zul-view-resolver-prefix=/zul
zk.resource-uri=/zkres

spring.security.oauth2.client.registration.keycloak.client-id=chnplc-service
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.client-secret=sxPFgUGklkiESCbPVNyRjiusjBwUeC5U
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
#spring.security.oauth2.client.registration.chnplc-web.redirect-uri=http://localhost:8601/chnplc-service/oauth2/authorization/chnplc-web
spring.security.oauth2.client.provider.keycloak.issuer-uri=https://keycloak.linkair-tech.cn/realms/chnplc

#spring.security.oauth2.client.registration.chnplc.client-id=chnplc-service
#spring.security.oauth2.client.registration.chnplc.provider=keycloak
#spring.security.oauth2.client.registration.chnplc.client-secret=sxPFgUGklkiESCbPVNyRjiusjBwUeC5U
#spring.security.oauth2.client.registration.chnplc.client-authentication-method=client_secret_basic
#spring.security.oauth2.client.registration.chnplc.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/YOUR_REALM_NAME
#spring.security.oauth2.client.provider.keycloak.jwks-uri=http://localhost:8080/realms/YOUR_REALM_NAME/protocol/openid-connect/certs
#logging.level.org.springframework.security=DEBUG