server.port=3001


spring.datasource.url=jdbc:h2:mem:purchase
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true

#spring.jpa.defer-datasource-initialization=true

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
#spring.datasource.initialization-mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.org.hibernate.envers.audit_table_prefix=AU_
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=

keycloak.auth-server-url=https://keycloak.linkair-tech.cn
keycloak.realm=chnplc
keycloak.resource=chnplc-service
keycloak.credentials.secret=sxPFgUGklkiESCbPVNyRjiusjBwUeC5U
#keycloak.public-client=true
keycloak.principal-attribute=preferred_username
#keycloak.bearer-only=true
#keycloak oauth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
spring.main.allow-circular-references=true
#server.servlet.context-path=/chnplc-service

springdoc.swagger-ui.operationsSorter=alpha
#For sorting tags alphabetically
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-operation-id=true
springdoc.api-docs.groups.enabled=true
#springdoc.group-configs[0].group=Purchase
#springdoc.group-configs[0].packages-to-scan=cn.liyun
#
#springdoc.group-configs[1].group=Sparrow
#springdoc.group-configs[1].packages-to-scan=cn.sparrowmini

application.name=@project.artifactId@
application.description=
build.version=@project.version@
build.timestamp=@timestamp@

#springdoc.api-docs.groups.enabled=true
#springdoc.group-configs[0].group=Purchase
#springdoc.group-configs[0].packages-to-scan=cn.liyun
#
#springdoc.group-configs[1].group=Sparrow
#springdoc.group-configs[1].packages-to-scan=cn.sparrowmini

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.cn.sparrowmini=DEBUG
logging.level.cn.liyuan=DEBUG


zk.homepage=index
zk.zul-view-resolver-prefix=/zul
zk.resource-uri=/zkres

spring.security.oauth2.client.registration.keycloak.client-id=chnplc-service
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.client-secret=sxPFgUGklkiESCbPVNyRjiusjBwUeC5U
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.provider.keycloak.issuer-uri=https://keycloak.linkair-tech.cn/realms/chnplc
