
kogito.persistence.type=jdbc
quarkus.devservices.enabled=false
%dev.quarkus.kogito.devservices.enabled=false
quarkus.swagger-ui.always-include=true
#kogito.generate.rest=true
# ??????????? Dev Services
#quarkus.datasource.devservices.enabled=false
kie.flyway.enabled=true
#vote.api=http://localhost:8300/toupiao-service
vote.api=http://localhost:8300/toupiao-service
quarkus.oidc.auth-server-url=https://keycloak.linkair-tech.cn/realms/chnplc
quarkus.oidc.client-id=chnplc-service
quarkus.oidc.credentials.secret=sxPFgUGklkiESCbPVNyRjiusjBwUeC5U

# ==== OIDC ??? Client Credentials????????? ====
quarkus.oidc-client.service-client.enabled=true
quarkus.oidc-client.service-client.auth-server-url=https://keycloak.linkair-tech.cn/realms/chnplc
quarkus.oidc-client.service-client.client-id=chnplc-service
quarkus.oidc-client.service-client.credentials.secret=sxPFgUGklkiESCbPVNyRjiusjBwUeC5U
quarkus.oidc-client.service-client.grant.type=client
quarkus.oidc-client.service-client.force-early-initialization=true

quarkus.http.auth.permission.public.paths=/q/swagger-ui/*,/q/openapi,/q/*,/graphql/*,/null/*,/*,/management/jobs,/management/processes,/null
quarkus.http.auth.permission.public.policy=permit

quarkus.security.auth.unprotected-paths=/management/jobs,/management/processes,/null

#quarkus.http.auth.permission.authenticated.paths=/*
#quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.log.category."io.quarkus.oidc.client".level=DEBUG


# ==== ???? ====
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/kogitobpm
quarkus.datasource.reactive.url=${QUARKUS_DATASOURCE_REACTIVE_URL:postgresql://localhost:5432/kogitobpm}
quarkus.hibernate-orm.database.generation=none
#quarkus.hibernate-orm.log.sql=true
quarkus.datasource.jdbc.additional-jdbc-properties.stringtype=unspecified
quarkus.hibernate-orm.jdbc.timezone=UTC
quarkus.datasource.transaction-management=xa
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


quarkus.index-dependency.sparrow-api.group-id=cn.sparrowmini
quarkus.index-dependency.sparrow-api.artifact-id=sparrow-bpm-api
quarkus.live-reload.instrumentation=true

# =======================
# ?????? (Task Notification Add-on)
# =======================

# ??????
jbpm.task.notification.enabled=true

# ?????? (??? classpath)
jbpm.task.notification.template.folder=templates/notifications

# ????????????
jbpm.task.notification.template.default=task-assigned-email.html

# =======================
# ??????? (Mail Add-on)
# =======================
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=fanmeijian@cn-plc.com
quarkus.mailer.host=smtp.exmail.qq.com
quarkus.mailer.port=465
#quarkus.mailer.ssl=true
quarkus.mailer.tls=true
quarkus.mailer.username=fanmeijian@cn-plc.com
quarkus.mailer.password=Cmdaho4BNnwNziWA
quarkus.mailer.auth=true
quarkus.mailer.mock=false
#quarkus.mailer.auth.login=REQUIRED



# ?? Kogito ????????

quarkus.kafka.devservices.enabled=false
kogito.addon.messaging.incoming.mode=embedded
kogito.service.url=http://localhost:8080/
kogito.jobs-service.url=http://localhost:8080/
#mp.messaging.outgoing.kogito-deadline-events.connector=smallrye-in-memory
#mp.messaging.incoming.kogito-deadline-consumer.connector=smallrye-in-memory
kogito.task-notification.enabled=false
kafka.bootstrap.servers=127.0.0.1:9092
mp.messaging.outgoing.kogito-deadline-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-deadline-events.topic=kogito-deadline-events
#mp.messaging.outgoing.kogito-deadline-events.bootstrap.servers=localhost:9092
#mp.messaging.outgoing.kogito-deadline-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.kogito-deadline-events.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

##
mp.messaging.incoming.kogito-deadline-consumer.connector=smallrye-kafka
mp.messaging.incoming.kogito-deadline-consumer.topic=kogito-deadline-events
#mp.messaging.incoming.kogito-deadline-consumer.bootstrap.servers=localhost:9092
#mp.messaging.incoming.kogito-deadline-consumer.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Enable Flyway to run migrations at startup
#quarkus.flyway.migrate-at-start=false

# Ensure the baseline is handled if you already have tables
#quarkus.flyway.baseline-on-migrate=false
#quarkus.flyway.locations=classpath:kie-flyway/db/jobs-service/postgresql
#quarkus.flyway.repair-at-start=true

#mp.messaging.outgoing.kogito-processinstances-events.bootstrap.servers=localhost:9092
mp.messaging.outgoing.kogito-processinstances-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-processinstances-events.topic=kogito-processinstances-events
mp.messaging.outgoing.kogito-processinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

#mp.messaging.outgoing.kogito-usertaskinstances-events.bootstrap.servers=localhost:9092
mp.messaging.outgoing.kogito-usertaskinstances-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-usertaskinstances-events.topic=kogito-usertaskinstances-events
mp.messaging.outgoing.kogito-usertaskinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

#mp.messaging.outgoing.kogito-variables-events.bootstrap.servers=localhost:9092
mp.messaging.outgoing.kogito-variables-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-variables-events.topic=kogito-variables-events
mp.messaging.outgoing.kogito-variables-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.kogito-processdefinitions-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-processdefinitions-events.topic=kogito-processdefinitions-events
mp.messaging.outgoing.kogito-processdefinitions-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.log.category."org.kie.kogito.task.notification".level=DEBUG
quarkus.log.category."org.kie.kogito.usertask.impl".level=TRACE

quarkus.arc.selected-alternatives=org.kie.kogito.jobs.embedded.*


#Data Index
kogito.apps.persistence.type=postgresql
kogito.data-index.domain-indexing=true
kogito.data-index.blocking=true