
#vote.api=http://localhost:8300/toupiao-service
vote.api=http://localhost:8300/toupiao-service
quarkus.oidc.auth-server-url=https://keycloak.linkair-tech.cn/realms/liyun-prd
quarkus.oidc.client-id=toupiao-service
quarkus.oidc.credentials.secret=4S0Bah39xZ6fsTxOYw0YoIuvrE5o4yGx

# ==== OIDC ??? Client Credentials????????? ====
quarkus.oidc-client.service-client.enabled=true
quarkus.oidc-client.service-client.auth-server-url=https://keycloak.linkair-tech.cn/realms/liyun-prd
quarkus.oidc-client.service-client.client-id=toupiao-service
quarkus.oidc-client.service-client.credentials.secret=4S0Bah39xZ6fsTxOYw0YoIuvrE5o4yGx
quarkus.oidc-client.service-client.grant.type=client
quarkus.oidc-client.service-client.force-early-initialization=true

quarkus.http.auth.permission.public.paths=/q/swagger-ui/*,/q/openapi
quarkus.http.auth.permission.public.policy=permit

quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# ==== ???? ====
quarkus.log.category."io.quarkus.oidc.client".level=DEBUG

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/kogito
quarkus.hibernate-orm.database.generation=update

# ??????? Jar ?????
quarkus.index-dependency.sparrow-api.group-id=cn.sparrowmini
quarkus.index-dependency.sparrow-api.artifact-id=sparrow-bpm-api

# ?? Hibernate ?????????????????
quarkus.hibernate-orm.log.sql=true

quarkus.datasource.jdbc.additional-jdbc-properties.stringtype=unspecified

#Hibernate
quarkus.hibernate-orm.jdbc.timezone=UTC
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# =======================
# ?????? (Task Notification Add-on)
# =======================

# ??????
jbpm.task.notification.enabled=true

# ?????? (??? classpath)
jbpm.task.notification.template.folder=templates/notifications

# ????????????
jbpm.task.notification.template.default=task-assigned-email.html

# =======================
# ??????? (Mail Add-on)
# =======================
quarkus.mailer.from=noreply@yourcompany.com
quarkus.mailer.host=smtp.yourcompany.com
quarkus.mailer.port=587
quarkus.mailer.username=noreply@yourcompany.com
quarkus.mailer.password=yourpassword
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.auth=true

quarkus.kafka.devservices.enabled=false

# ?? Kogito ????????
kogito.addon.messaging.incoming.mode=embedded


kafka.bootstrap.servers=116.205.190.93:5092
mp.messaging.outgoing.kogito-deadline-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-deadline-events.topic=kogito-deadline-events
mp.messaging.outgoing.kogito-deadline-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.kogito-deadline-consumer.connector=smallrye-kafka
mp.messaging.incoming.kogito-deadline-consumer.topic=kogito-deadline-events
mp.messaging.incoming.kogito-deadline-consumer.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer