export * from './caseInstanceAdministration.service';
import { CaseInstanceAdministrationService } from './caseInstanceAdministration.service';
export * from './caseInstances.service';
import { CaseInstancesService } from './caseInstances.service';
export * from './caseQueries.service';
import { CaseQueriesService } from './caseQueries.service';
export * from './customQueries.service';
import { CustomQueriesService } from './customQueries.service';
export * from './dMNModels.service';
import { DMNModelsService } from './dMNModels.service';
export * from './documents.service';
import { DocumentsService } from './documents.service';
export * from './jobs.service';
import { JobsService } from './jobs.service';
export * from './kIEServerAndKIEContainers.service';
import { KIEServerAndKIEContainersService } from './kIEServerAndKIEContainers.service';
export * from './kIESessionAssets.service';
import { KIESessionAssetsService } from './kIESessionAssets.service';
export * from './processAndTaskDefinitions.service';
import { ProcessAndTaskDefinitionsService } from './processAndTaskDefinitions.service';
export * from './processAndTaskForms.service';
import { ProcessAndTaskFormsService } from './processAndTaskForms.service';
export * from './processImages.service';
import { ProcessImagesService } from './processImages.service';
export * from './processInstanceAdministration.service';
import { ProcessInstanceAdministrationService } from './processInstanceAdministration.service';
export * from './processInstances.service';
import { ProcessInstancesService } from './processInstances.service';
export * from './processQueries.service';
import { ProcessQueriesService } from './processQueries.service';
export * from './staticFilesEndpointBPM.service';
import { StaticFilesEndpointBPMService } from './staticFilesEndpointBPM.service';
export * from './taskInstanceAdministration.service';
import { TaskInstanceAdministrationService } from './taskInstanceAdministration.service';
export * from './taskInstances.service';
import { TaskInstancesService } from './taskInstances.service';
export * from './jbpmExt.service';
import { JbpmExtService } from './jbpmExt.service';
export const APIS = [CaseInstanceAdministrationService, CaseInstancesService, CaseQueriesService, CustomQueriesService, DMNModelsService, DocumentsService, JobsService, KIEServerAndKIEContainersService, KIESessionAssetsService, ProcessAndTaskDefinitionsService, ProcessAndTaskFormsService, ProcessImagesService, ProcessInstanceAdministrationService, ProcessInstancesService, ProcessQueriesService, StaticFilesEndpointBPMService, TaskInstanceAdministrationService, TaskInstancesService, JbpmExtService];
